# Generated by Django 5.2.7 on 2025-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darijums',
            name='aksesuars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='apdr_iekartas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='atv_iekarta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='nom_iekarta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='pieslegums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='pil_iekarta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='viedpaligs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darijums',
            name='viedtelevizija',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
