# Generated by Django 5.2.7 on 2025-10-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darijums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieslegums', models.IntegerField()),
                ('atv_iekarta', models.IntegerField()),
                ('nom_iekarta', models.IntegerField()),
                ('pil_iekarta', models.IntegerField()),
                ('viedpaligs', models.IntegerField()),
                ('apdr_iekartas', models.IntegerField()),
                ('aksesuars', models.IntegerField()),
                ('viedtelevizija', models.IntegerField()),
                ('datums', models.DateTimeField(auto_now_add=True)),
                ('lietotajs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieslegumi', models.IntegerField()),
                ('iekartas', models.IntegerField()),
                ('viedpaligi', models.IntegerField()),
                ('aksesuari', models.IntegerField()),
                ('atv_proprocija', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apdr_proporcija', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viedtelevizija', models.IntegerField()),
                ('menesis', models.CharField(max_length=20)),
                ('gads', models.IntegerField()),
                ('lietotajs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
