# Generated by Django 5.2.6 on 2025-10-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0002_alter_darijums_aksesuars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darijums',
            options={'ordering': ['-datums']},
        ),
    ]
