# Generated by Django 5.2.6 on 2025-10-12 16:40

import baze.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0003_alter_darijums_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='gads',
            field=models.IntegerField(default=baze.models.current_year),
        ),
        migrations.AlterField(
            model_name='plans',
            name='menesis',
            field=models.CharField(choices=[('1', 'Janvāris'), ('2', 'Februāris'), ('3', 'Marts'), ('4', 'Aprīlis'), ('5', 'Maijs'), ('6', 'Jūnijs'), ('7', 'Jūlijs'), ('8', 'Augusts'), ('9', 'Septembris'), ('10', 'Oktobris'), ('11', 'Novembris'), ('12', 'Decembris')], default='10', max_length=2),
        ),
    ]
