# Generated by Django 5.2.6 on 2025-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0004_alter_plans_gads_alter_plans_menesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='apdr_proporcija',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plans',
            name='atv_proprocija',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
