# Generated by Django 5.2.6 on 2025-10-14 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0005_alter_plans_apdr_proporcija_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plans',
            constraint=models.UniqueConstraint(fields=('lietotajs', 'menesis', 'gads'), name='viens_menesis_gads'),
        ),
    ]
