# Generated by Django 5.2.7 on 2025-10-28 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0006_plans_viens_menesis_gads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darijums',
            name='datums',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
