# Generated by Django 5.2.7 on 2025-11-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0007_alter_darijums_datums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menesis_id', models.PositiveSmallIntegerField(unique=True)),
                ('nosaukums', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['menesis_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='plans',
            name='viens_menesis_gads',
        ),
        migrations.AlterField(
            model_name='plans',
            name='menesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baze.menesis'),
        ),
    ]
