# Generated by Django 5.2.7 on 2025-11-13 15:31

import baze.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0008_menesis_remove_plans_viens_menesis_gads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='menesis',
            field=models.ForeignKey(default=baze.models.menesis_tagad, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baze.menesis'),
        ),
    ]
