# Generated by Django 5.2.7 on 2025-11-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0009_alter_plans_menesis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='atv_proprocija',
            new_name='atv_proporcija',
        ),
    ]
