# Generated by Django 5.2.7 on 2025-12-03 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0010_rename_atv_proprocija_plans_atv_proporcija'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVeikals',
            new_name='LietotajsVeikals',
        ),
        migrations.RenameField(
            model_name='lietotajsveikals',
            old_name='user',
            new_name='lietotajs',
        ),
    ]
