# Generated by Django 5.2.7 on 2025-12-03 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baze', '0011_rename_userveikals_lietotajsveikals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menesis',
            new_name='Month',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='Veikals',
            new_name='Store',
        ),
        migrations.RenameModel(
            old_name='Darijums',
            new_name='StoreRecord',
        ),
        migrations.RenameModel(
            old_name='LietotajsVeikals',
            new_name='UserStore',
        ),
    ]
